export const SCREEN_NAMES = {
  Home: 'Home',
  DynamicSizeItemScroll: 'DynamicSizeItemScroll',
  DynamicSizeItemScrollUsingMoti: 'DynamicSizeItemScrollUsingMoti',
  PhoneRingIndicatorWave: 'PhoneRingIndicatorWave',
  GalleryViewSyncFlatLists: 'GalleryViewSyncFlatLists',
  ScrollItemAnimationEffect: 'ScrollItemAnimationEffect',
  CarouselAnimation: 'CarouselAnimation',
  ThreeDCarouselAnimation: 'ThreeDCarouselAnimation',
  FirstReanimatedAnimation: 'FirstReanimatedAnimation',
  AnimatingStyleAndProps: 'AnimatingStyleAndProps',
  ApplyingModifiers: 'ApplyingModifiers',
  HandlingGestures: 'HandlingGestures',
  WithTimingExample: 'WithTimingExample',
  WithSpringExample: 'WithSpringExample',
  WithDecayExample: 'WithDecayExample',
  WithDelayExample: 'WithDelayExample',
  WithDerivedValueExample: 'WithDerivedValueExample',
  CancelAnimationExample: 'CancelAnimationExample',
  ScrollToExample: 'ScrollToExample',
  AnimatedKeyboardExample: 'AnimatedKeyboardExample',
} as const;
